/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-light': 'rgb(var(--rgb-accent) / <alpha-value>)',
        'surface-tint': 'rgb(var(--rgb-soft) / <alpha-value>)',
        ink: 'rgb(var(--rgb-text) / <alpha-value>)',
        page: 'rgb(var(--rgb-bg) / <alpha-value>)',
        'ability-gap': 'rgb(var(--rgb-ability-gap) / <alpha-value>)',
        'ability-gap-text': 'var(--color-ability-gap-text)',
        'ability-gap-bg': 'var(--color-ability-gap-bg)',
        'ability-gap-border': 'var(--color-ability-gap-border)',
        ambiguous: 'rgb(var(--rgb-ambiguous) / <alpha-value>)',
        'ambiguous-bg': 'var(--color-ambiguous-bg)',
        'ambiguous-border': 'var(--color-ambiguous-border)',
        'ambiguous-text': 'var(--color-ambiguous-text)',
        'danger-bg': 'var(--color-danger-bg)',
        'danger-border': 'var(--color-danger-border)',
        'success-bg': 'var(--color-success-bg)',
        'success-border': 'var(--color-success-border)',
        overlay: 'rgb(var(--rgb-overlay) / <alpha-value>)',
        bg: 'rgb(var(--bg) / <alpha-value>)',
        surface: 'rgb(var(--surface) / <alpha-value>)',
        text: 'rgb(var(--text) / <alpha-value>)',
        heading: 'rgb(var(--heading) / <alpha-value>)',
        muted: 'rgb(var(--muted) / calc(var(--muted-opacity) * <alpha-value>))',
        border: 'rgb(var(--border) / calc(var(--border-opacity) * <alpha-value>))',
        track: 'rgb(var(--track) / var(--track-opacity))',
        primary: 'rgb(var(--primary) / <alpha-value>)',
        'primary-fg': 'rgb(var(--primary-fg) / <alpha-value>)',
        'primary-hover': 'rgb(var(--primary-hover) / <alpha-value>)',
        'primary-hover-fg': 'rgb(var(--primary-hover-fg) / <alpha-value>)',
        accent: 'rgb(var(--accent) / <alpha-value>)',
        'accent-fg': 'rgb(var(--accent-fg) / <alpha-value>)',
        sidebar: 'rgb(var(--sidebar) / <alpha-value>)',
        'sidebar-fg': 'rgb(var(--sidebar-fg) / <alpha-value>)',
        danger: 'rgb(var(--danger) / <alpha-value>)',
        warn: 'rgb(var(--warn) / <alpha-value>)',
        success: 'rgb(var(--rgb-success) / <alpha-value>)',
        'success-text': 'var(--color-success-text)',
        info: 'rgb(var(--rgb-accent) / <alpha-value>)',
        soft: 'rgb(var(--rgb-soft) / <alpha-value>)',
        'soft-text': 'rgb(var(--rgb-soft-text) / <alpha-value>)',
      },
      boxShadow: {
        soft: '0 1px 2px rgb(var(--rgb-shadow) / 0.05), 0 4px 16px rgb(var(--rgb-shadow) / 0.06)',
      },
    },
  },
  plugins: [],
}
